version: '3.8'

services:
    nuxt:
        image: node:14.17
        volumes:
            - ./:/home/webcompose
            #ports:
            # - 8889:3000
            #   expose:
            # - 3000
        expose:
            - 3000
        environment:
            - HOST=0.0.0.0
            - VIRTUAL_HOST=yourdomain.com,www.yourdomain.com
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=yourdomain.com,www.yourdomain.com
        command: bash -c ' cd /home/webcompose/nuxt && npm i && npm run start'
    django:
        image: python:3.8.12-slim-buster
        volumes:
            - ./:/home/webcompose
            #    ports:
            #- 8887:8000
        expose:
            - 8000
        env_file:
            - ./.env
        environment:
            - HOST=0.0.0.0
            - VIRTUAL_HOST=api.yourdomain.com
            - VIRTUAL_PORT=8000
            - LETSENCRYPT_HOST=api.yourdomain.com
        command: bash -c ' cd /home/webcompose/django/ && pip install -r requirement.txt
            && cd webcompose && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --reload webcompose.wsgi:application' 
                # && python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres
    postgres:
        image: postgres:13.0-alpine
        volumes:
            - ./postgres:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env.postgres

    # nginx:
    #         #image: nginx:latest
    #         build: ./nginx
    #         volumes:
    #                 - ./:/home/webcompose
    #                 # - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    #                 # - /./nginx/nginx.conf:/etc/nginx/conf.d
    #         ports:
    #                 - 80:80
    #         depends_on:
    #                 - nuxt
    #                 - django

    nginx-proxy:
        build: ./nginx-proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/home/webcompose
            - ./nginx-proxy/certs:/etc/nginx/certs
            - ./nginx-proxy/html:/usr/share/nginx/html
            - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - django
            - nuxt
    nginx-proxy-letsencrypt:
        image: nginxproxy/acme-companion
            # env_file:
            # - ./.env.prod.proxy-companion
        environment:
            - DEFAULT_EMAIL=jun@yourdomain.co.kr
            # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
            # - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./nginx-proxy/acme:/etc/acme.sh
        depends_on:
            - nginx-proxy
