version: "3.8"

services:
  nuxt:
    image: node:14.17
    volumes:
      - ./nuxt:/container/nuxt
    expose:
      - 3000
    command: 
      bash -c '
      cd /container/nuxt
      && npm run dev
      && tail -F /dev/null'
      # && npm ci 
            # insert it to before 'npm run dev' when doesn't have node_modules
            # also package-lock.json doesn't exist

  django:
    build: ./django
    volumes:
      - ./django:/container/django
    expose:
      - 8000
    env_file:
      - ./django/.env.dev
    command:
      bash -c '
      cd /container/django/webcompose
      && poetry config virtualenvs.in-project true
      && poetry install --no-interaction
      && poetry run python manage.py collectstatic --noinput
      && poetry run gunicorn --bind 0.0.0.0:8000 --reload webcompose.wsgi:application
      && tail -F /dev/null'
      # && poetry update
            # Use this command if you want to update dependencies latest 
            # or to fix dependencies version error.
      
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.postgres

  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/container/nginx
      - ./django/webcompose/static:/container/django/webcompose/static
    ports:
      - 80:80
    depends_on:
      - nuxt
      - django
